### ISSUE TITLE
Exception when trying to load sequences

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/PyTilengine#3]
I'm trying to load some animation sequences using the following:

```python
from tilengine import SequencePack
seq_pack = SequencePack.fromfile('sequences.sqx')
```
But I get the following error:

```
Traceback (most recent call last):
  File "error-test.py", line 6, in <module>
    seq_pack = SequencePack.fromfile('sequences.sqx')
  File "/home/daniel/development/game/tilengine.py", line 1484, in fromfile
    _raise_exception()
  File "/home/daniel/development/game/tilengine.py", line 304, in _raise_exception
    raise TilengineException(error_string.decode())
tilengine.TilengineException: 'Null pointer as required argument'
```

Is this a bug or am I missing something?

**Comment by megamarc** [comment]
Hi Daniel,
What version of the Tilengine .so file are you targeting? Trying to load a non-existent `SequencePack` resource should throw the following exception message:
`tilengine.TilengineException: 'Resource file not found'`
I've checked it against Tilengine.dll 2.1.2 64-bit for Windows

**Comment by danielgholmes** [comment]
I'm using Ubuntu 18.04 with Tilengine 2.4.0. Can you confirm if you also get this error on this version?

**Comment by megamarc** [comment]
The problem is that you're trying to load resources without having initialised the engine first with `Engine.create()`. 

Try this instead:
```python
from tilengine import Engine, SequencePack
engine = Engine.create(400, 240, 1, 0, 20)
seq_pack = SequencePack.fromfile('sequences.sqx')
```
Now you should get the proper error message. Let me know!
